### Get page
GET http://localhost:8080/clients?page=0&size=3&sort=firstname,DESC

### Get one
GET http://localhost:8080/clients/13

### Delete
DELETE http://localhost:8080/clients/444

### Add client
POST http://localhost:8080/clients
Content-Type: application/json

{
  "firstname": "Андрей",
  "lastname": "Dub",
  "patronymic": "Puk",
  "dateOfBirth": "2023-09-09",
  "sex": "F",
  "address": "<budka",
  "phoneNumberHome": "159300140",
  "phoneNumber": "293760895",
  "email": "mark23_putyato@mail.ru",
  "isRetired": true,
  "monthlyIncome": 0,
  "passport": {
    "passportId": "5260802K000PB8",
    "passportSeries": "KH",
    "passportNumber": "2626914",
    "passportIssuer": "Oshm",
    "passportIssuedDate": "2022-09-09",
    "passportAddress": "minks",
    "placeOfBirth": "bubu"
  },
  "cityActualId": 1,
  "maritalStatusId": 1,
  "citizenshipId": 1,
  "disabilityId": 1
}

### update
PUT http://localhost:8080/clients/26
Content-Type: application/json

{
  "firstname": "Андрей",
  "lastname": "Dub",
  "patronymic": "Puk",
  "dateOfBirth": "2022-09-09",
  "sex": "F",
  "address": "<budka",
  "phoneNumberHome": "314141",
  "phoneNumber": "293760895",
  "email": "mark23_putyato@mail.ru",
  "isRetired": true,
  "monthlyIncome": 0,
  "passport": {
    "passportId": "5260802K000PB9",
    "passportSeries": "KH",
    "passportNumber": "2626919",
    "passportIssuer": "Oshm",
    "passportIssuedDate": "2022-09-09",
    "passportAddress": "minks",
    "placeOfBirth": "bubu"
  },
  "cityActualId": 1,
  "maritalStatusId": 1,
  "citizenshipId": 1,
  "disabilityId": 1
}
