spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/bank
    driver-class-name: org.postgresql.Driver
