/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 03-фев-2023 12:38:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS citizenship CASCADE
;

DROP TABLE IF EXISTS city CASCADE
;

DROP TABLE IF EXISTS client CASCADE
;

DROP TABLE IF EXISTS disability CASCADE
;

DROP TABLE IF EXISTS marital_status CASCADE
;

DROP TABLE IF EXISTS passport CASCADE
;

/* Create Tables */

CREATE TABLE citizenship
(
	id bigserial NOT NULL,
	name varchar(255) NOT NULL
)
;

CREATE TABLE city
(
	id bigserial NOT NULL,
	name varchar(255) NOT NULL
)
;

CREATE TABLE client
(
	passport_id bigint NOT NULL,
	firstname varchar(255) NOT NULL,
	lastname varchar(255) NOT NULL,
	patronymic varchar(255) NOT NULL,
	date_of_birth date NOT NULL,
	sex varchar(2) NOT NULL,
	city_actual_id bigint NOT NULL,
	address varchar(255) NOT NULL,
	phone_number_home varchar(16) NULL,
	phone_number varchar(16) NULL,
	email varchar(255) NULL,
	is_retired boolean NOT NULL   DEFAULT FALSE,
	monthly_income integer NULL,
	marital_status_id bigint NOT NULL,
	citizenship_id bigint NOT NULL,
	disability_id bigint NOT NULL
)
;

CREATE TABLE disability
(
	id bigserial NOT NULL,
	name varchar(255) NOT NULL
)
;

CREATE TABLE marital_status
(
	id bigserial NOT NULL,
	name varchar(255) NOT NULL
)
;

CREATE TABLE passport
(
	id bigserial NOT NULL,
	passport_series varchar(32) NOT NULL,
	passport_number varchar(255) NOT NULL,
	passport_issuer varchar(255) NOT NULL,
	passport_id varchar(255) NOT NULL,
	passport_address varchar(255) NOT NULL,
	passport_issued_date date NOT NULL,
	place_of_birth varchar(255) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE citizenship ADD CONSTRAINT PK_citizenship
	PRIMARY KEY (id)
;

ALTER TABLE citizenship 
  ADD CONSTRAINT UNQ_citiezenship_name UNIQUE (name)
;

ALTER TABLE city ADD CONSTRAINT PK_city
	PRIMARY KEY (id)
;

ALTER TABLE client ADD CONSTRAINT PK_client
	PRIMARY KEY (passport_id)
;

ALTER TABLE client 
  ADD CONSTRAINT UNQ_client_email UNIQUE (email)
;

ALTER TABLE client ADD CONSTRAINT CHK_non_negative_monthly_income CHECK (monthly_income >= 0)
;

CREATE INDEX IXFK_client_citizenship ON client (citizenship_id ASC)
;

CREATE INDEX IXFK_client_city ON client (city_actual_id ASC)
;

CREATE INDEX IXFK_client_client_passport ON client (passport_id ASC)
;

CREATE INDEX IXFK_client_disability ON client (disability_id ASC)
;

CREATE INDEX IXFK_client_marital_status ON client (marital_status_id ASC)
;

ALTER TABLE disability ADD CONSTRAINT PK_disability
	PRIMARY KEY (id)
;

ALTER TABLE disability 
  ADD CONSTRAINT UNQ_disability_name UNIQUE (name)
;

ALTER TABLE marital_status ADD CONSTRAINT PK_marital_status
	PRIMARY KEY (id)
;

ALTER TABLE marital_status 
  ADD CONSTRAINT UNQ_marital_status_name UNIQUE (name)
;

ALTER TABLE passport ADD CONSTRAINT PK_client_passport
	PRIMARY KEY (id)
;

ALTER TABLE passport 
  ADD CONSTRAINT UNQ_passport_series_number UNIQUE (passport_number)
;

ALTER TABLE passport 
  ADD CONSTRAINT UNQ_passport_id UNIQUE (passport_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE client ADD CONSTRAINT FK_client_citizenship
	FOREIGN KEY (citizenship_id) REFERENCES citizenship (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE client ADD CONSTRAINT FK_client_city
	FOREIGN KEY (city_actual_id) REFERENCES city (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE client ADD CONSTRAINT FK_client_client_passport
	FOREIGN KEY (passport_id) REFERENCES passport (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE client ADD CONSTRAINT FK_client_disability
	FOREIGN KEY (disability_id) REFERENCES disability (id) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE client ADD CONSTRAINT FK_client_marital_status
	FOREIGN KEY (marital_status_id) REFERENCES marital_status (id) ON DELETE Restrict ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 
